import type { Metadata } from "next";
import { Merriweather, Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";

const merriWeather = Merriweather({
  subsets: ['latin'], 
  weight: ['400', '700'], 
  style: 'normal', 
  variable:"--font-merriWeather"
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600'], // Regular and semi-bold weights for body text
  style: 'normal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${openSans.className} ${merriWeather.variable}  antialiased`}
        >
          <ClerkLoading><div className="flex justify-center items-center h-screen w-full">
            Loading...
          </div></ClerkLoading>
          <ClerkLoaded>
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
